# global parameters
model_name: attbilstm  # 'han', 'fasttext', 'attbilstm', 'textcnn', 'transformer'
                       # refer to README.md for more info about each model

# dataset parameters
dataset: instance_severity  # 'ag_news'
                  # refer to README.md for more info about each dataset
dataset_path: <...>  # folder with dataset
output_path: <...>  # folder with data files saved by preprocess.py

# preprocess parameters
word_limit: 500
min_word_count: 5

# word embeddings parameters
emb_pretrain: False  # false: initialize embedding weights randomly
                    # true: load pre-trained word embeddings
emb_folder: <...>  # only makes sense when `emb_pretrain: True`
emb_filename: glove.6B.300d.txt  # or incident_word2vec.model only makes sense when `emb_pretrain: True`
emb_size: 768  # word embedding size
               # only makes sense when `emb_pretrain: False`
fine_tune_word_embeddings: True  # fine-tune word embeddings?

# model parameters
rnn_size: 768  # bi-RNN size
rnn_layers: 1  # number of layers in bi-RNN
dropout: 0.3  # dropout

# checkpoint saving parameters
checkpoint_path: <...>  # path to save checkpoints, null if never save checkpoints
checkpoint_basename: checkpoint  # basename of the checkpoint

# training parameters
start_epoch: 0  # start at this epoch
batch_size: 128  # batch size
lr: 0.001  # learning rate
lr_decay: 0.9  # a factor to multiply learning rate with (0, 1)
workers: 4  # number of workers for loading data in the DataLoader
num_epochs: 10  # number of epochs to run
grad_clip: null  # clip gradients at this value, null if never clip gradients
print_freq: 500  # print training status every __ batches
checkpoint: null  # path to model checkpoint, null if none
# tensorboard
tensorboard: True  # enable tensorboard or not?
log_dir: <...> # folder to save logs for tensorboard, only makes sense when `tensorboard: True`
